name: "P6 GHA: Setups Node"
description: "P6 GHA: Setups Node"
author: "Philip M. Gollucci"

inputs:
  node-version:
    description: "Node.js version to install (e.g., 24.9.0)"
    required: false
    default: "24.9.0"

  pnpm-version:
    description: "pnpm version to activate via Corepack (e.g., 10.18.2)"
    required: false
    default: "10.18.2"

runs:
  using: "composite"
  steps:
    - name: Install Node.js
      shell: bash
      run: |
        NODE_VERSION="${{ inputs.node-version }}"
        curl -fsSL "https://nodejs.org/dist/v${NODE_VERSION}/node-v${NODE_VERSION}-linux-x64.tar.xz" -o "node-v${NODE_VERSION}-linux-x64.tar.xz"
        sudo tar -xJf "node-v${NODE_VERSION}-linux-x64.tar.xz" -C /usr/local
        sudo chown -R $(whoami) "/usr/local/node-v${NODE_VERSION}-linux-x64"
        rm -f "node-v${NODE_VERSION}-linux-x64.tar.xz"
        echo "/usr/local/node-v${NODE_VERSION}-linux-x64/bin" >> $GITHUB_PATH

    - name: Enable pnpm via Corepack
      shell: bash
      run: |
        PNPM_VERSION="${{ inputs.pnpm-version }}"
        corepack enable
        if [ -e package.json ]; then
          corepack prepare "pnpm@${PNPM_VERSION}" --activate
        fi

    - name: Check Node
      shell: bash
      run: |
        set +e
        which node
        which npm
        which pnpm
        which corepack
        node -v
        npm -v
        pnpm --version || echo "pnpm not installed"
        corepack --version
        echo $PATH

    - name: Install pnpm and dependencies
      shell: bash
      run: |
        if [ -e package.json ]; then
          pnpm install
        fi
