name: "P6 GHA: Setups Node"
description: "P6 GHA: Setups Node"
author: "Philip M. Gollucci"
runs:
  using: "composite"
  steps:
    - name: Install Node.js
      shell: bash
      run: |
        curl -fsSL https://nodejs.org/dist/v22.13.0/node-v22.13.0-linux-x64.tar.xz -o node-v22.13.0-linux-x64.tar.xz
        sudo tar -xJf node-v22.13.0-linux-x64.tar.xz -C /usr/local
        rm -f node-v22.13.0-linux-x64.tar.xz
        echo "/usr/local/node-v22.13.0-linux-x64/bin" >> $GITHUB_PATH
    - name: Enable pnpm via Corepack
      shell: bash
      run: |
        corepack enable
        corepack prepare pnpm@latest --activate
    - name: Check Node
      shell: bash
      run: |
        set +e
        which node
        which npm
        which pnpm
        which corepack
        node -v
        npm -v
        pnpm --version || echo "pnpm not installed"
        corepack --version
        echo $PATH
    - name: Install pnpm and dependencies
      shell: bash
      run: pnpm install
